# Generated by Django 3.1.1 on 2020-09-27 11:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('st_name', models.CharField(max_length=100)),
                ('st_total_footfall', models.IntegerField()),
                ('st_returning_footfall', models.IntegerField()),
                ('st_time_spent', models.FloatField()),
                ('st_tot_dep_visited', models.IntegerField()),
                ('st_tot_departments', models.IntegerField()),
                ('st_avg_dep_time', models.FloatField()),
                ('st_bounce_rate', models.FloatField()),
            ],
        ),
    ]
